### ISSUE TITLE
Double Hashing of Password while Updating Profile

### ISSUE THREAD

**Issue by jalajcodes** [nomadcoders/nuber-eats-backend#1]
Inside the user entity, in our hashPassword method we don't check if the password is modified or not. Due to this when we only update the email of our profile the hash method runs and hashes the already hashed password.

**Comment by kyujonglee** [comment]
we fixed it #6.3 :)

**Comment by jalajcodes** [comment]
@kyujonglee yeah, I saw that video next day and forgot to close the issue.
